import Darwin
import Foundation
import Testing

@testable import EvieCore

@Suite("OmniVoice batch TTS adapter")
struct OmniVoiceBatchTTSAdapterTests {
  @Test("sends private request content only through stdin and restricts temporary files")
  func privateStandardInputAndPermissions() async throws {
    let fixture = try Fixture(script: Self.successScript)
    defer { fixture.remove() }
    let adapter = try OmniVoiceBatchTTSAdapter(configuration: fixture.configuration())

    let audio = try await adapter.synthesize(fixture.request())
    let requestDirectory = audio.fileURL.deletingLastPathComponent()
    let evieDirectory = fixture.temporaryRootURL.deletingLastPathComponent()

    #expect(try fixture.permissions(at: evieDirectory) == 0o700)
    #expect(try fixture.permissions(at: fixture.temporaryRootURL) == 0o700)
    #expect(try fixture.permissions(at: requestDirectory) == 0o700)
    #expect(try fixture.permissions(at: audio.fileURL) == 0o600)
    let output = try Data(contentsOf: audio.fileURL)
    #expect(output.count == 46)
    #expect(output.prefix(4) == Data("RIFF".utf8))
    #expect(output[8..<12] == Data("WAVE".utf8))

    let names = try Set(
      FileManager.default.contentsOfDirectory(
        at: requestDirectory,
        includingPropertiesForKeys: nil
      ).map(\.lastPathComponent)
    )
    #expect(names == ["cache", "speech.wav"])

    audio.discard()
    #expect(!FileManager.default.fileExists(atPath: requestDirectory.path))
  }

  @Test("treats a successful exit without generated bytes as a failure and cleans up")
  func missingOutput() async throws {
    let fixture = try Fixture(script: Self.emptyOutputScript)
    defer { fixture.remove() }
    let adapter = try OmniVoiceBatchTTSAdapter(configuration: fixture.configuration())

    do {
      _ = try await adapter.synthesize(fixture.request())
      Issue.record("Expected an output validation failure.")
    } catch let error as EvieTTSError {
      #expect(error == .outputMissing)
    }

    #expect(try fixture.requestDirectories().isEmpty)
  }

  @Test("rejects a non-WAV output and cleans it up")
  func nonWaveOutput() async throws {
    let fixture = try Fixture(script: Self.nonWaveOutputScript)
    defer { fixture.remove() }
    let adapter = try OmniVoiceBatchTTSAdapter(configuration: fixture.configuration())

    do {
      _ = try await adapter.synthesize(fixture.request())
      Issue.record("Expected a WAV validation failure.")
    } catch let error as EvieTTSError {
      #expect(error == .outputMissing)
    }

    #expect(try fixture.requestDirectories().isEmpty)
  }

  @Test("rejects an oversized output before returning it")
  func oversizedOutput() async throws {
    let fixture = try Fixture(script: Self.oversizedOutputScript)
    defer { fixture.remove() }
    let adapter = try OmniVoiceBatchTTSAdapter(configuration: fixture.configuration())

    do {
      _ = try await adapter.synthesize(fixture.request())
      Issue.record("Expected an output-size validation failure.")
    } catch let error as EvieTTSError {
      #expect(error == .outputMissing)
    }

    #expect(try fixture.requestDirectories().isEmpty)
  }

  @Test("times out and terminates the isolated child process group")
  func timeout() async throws {
    let fixture = try Fixture(script: Self.longRunningScript)
    defer { fixture.remove() }
    try fixture.warmUpExecutable()
    let adapter = try OmniVoiceBatchTTSAdapter(
      configuration: fixture.configuration(timeout: 0.5, gracePeriod: 0.05)
    )

    let start = ContinuousClock.now
    do {
      _ = try await adapter.synthesize(fixture.request())
      Issue.record("Expected a timeout.")
    } catch let error as EvieTTSError {
      #expect(error == .timedOut)
    }
    #expect(start.duration(to: .now) < .seconds(2))
    let childIdentifier = try await fixture.recordedChildIdentifier()
    try await fixture.expectChildStopped(childIdentifier)
    #expect(try fixture.requestDirectories().isEmpty)
  }

  @Test("task cancellation terminates the isolated child process group")
  func cancellation() async throws {
    let fixture = try Fixture(script: Self.longRunningScript)
    defer { fixture.remove() }
    let adapter = try OmniVoiceBatchTTSAdapter(
      configuration: fixture.configuration(timeout: 5, gracePeriod: 0.05)
    )
    let task = Task {
      try await adapter.synthesize(fixture.request())
    }

    let childIdentifier = try await fixture.recordedChildIdentifier()
    task.cancel()

    do {
      _ = try await task.value
      Issue.record("Expected cancellation.")
    } catch is CancellationError {
      // Expected.
    }
    try await fixture.expectChildStopped(childIdentifier)
    #expect(try fixture.requestDirectories().isEmpty)
  }

  @Test("rejects non-file executables without launching a process")
  func invalidExecutable() throws {
    let fixture = try Fixture(script: Self.successScript)
    defer { fixture.remove() }
    var configuration = fixture.configuration()
    configuration.executableURL = URL(string: "relative-helper")!

    #expect(throws: EvieTTSError.invalidConfiguration) {
      try OmniVoiceBatchTTSAdapter(configuration: configuration)
    }
  }

  @Test("rejects an offline cache without the tokenizer snapshot")
  func missingTokenizerSnapshot() throws {
    let fixture = try Fixture(script: Self.successScript)
    defer { fixture.remove() }
    let snapshotsURL = fixture.huggingFaceCacheURL
      .appendingPathComponent("hub", isDirectory: true)
      .appendingPathComponent(
        "models--eustlb--higgs-audio-v2-tokenizer",
        isDirectory: true
      )
      .appendingPathComponent("snapshots", isDirectory: true)
    try FileManager.default.removeItem(at: snapshotsURL)

    #expect(throws: EvieTTSError.invalidConfiguration) {
      try OmniVoiceBatchTTSAdapter(configuration: fixture.configuration())
    }
  }
}

extension OmniVoiceBatchTTSAdapterTests {
  fileprivate static let successScript = """
    #!/bin/sh
    set -eu
    umask 077
    res_dir=''
    test_list=''
    model_dir=''
    for argument in "$@"; do
      case "$argument" in
        *PRIVATE-TEXT-SENTINEL*|*PRIVATE-REFERENCE-SENTINEL*) exit 70 ;;
      esac
    done
    while [ "$#" -gt 0 ]; do
      key="$1"
      value="$2"
      shift 2
      case "$key" in
        --res_dir) res_dir="$value" ;;
        --test_list) test_list="$value" ;;
        --model) model_dir="$value" ;;
      esac
    done
    [ "$test_list" = '/dev/stdin' ] || exit 71
    [ "${HF_HUB_OFFLINE-}" = '1' ] || exit 72
    [ "${TRANSFORMERS_OFFLINE-}" = '1' ] || exit 73
    [ "${HF_DATASETS_OFFLINE-}" = '1' ] || exit 74
    [ "${HF_HUB_DISABLE_TELEMETRY-}" = '1' ] || exit 75
    [ "${HF_HUB_DISABLE_IMPLICIT_TOKEN-}" = '1' ] || exit 82
    [ "${HF_HOME-}" = "${model_dir%/model}/huggingface" ] || exit 83
    [ "${PYTHONNOUSERSITE-}" = '1' ] || exit 76
    if [ "${HTTP_PROXY+present}" = 'present' ]; then exit 77; fi
    if [ "${HOME+present}" = 'present' ]; then exit 78; fi
    [ "${TMPDIR-}" = "$res_dir/" ] || exit 79
    [ "${XDG_CACHE_HOME-}" = "$res_dir/cache" ] || exit 84
    case "${PYTHONPYCACHEPREFIX-}" in "$res_dir/cache"/*) ;; *) exit 85 ;; esac
    case "${TORCH_HOME-}" in "$res_dir/cache"/*) ;; *) exit 86 ;; esac
    IFS= read -r request
    case "$request" in *PRIVATE-TEXT-SENTINEL*) ;; *) exit 80 ;; esac
    case "$request" in *PRIVATE-REFERENCE-SENTINEL*) ;; *) exit 81 ;; esac
    printf 'RIFF&\\000\\000\\000WAVEfmt \\020\\000\\000\\000\\001\\000\\001\\000\\300]\\000\\000\\200\\273\\000\\000\\002\\000\\020\\000data\\002\\000\\000\\000\\000\\000' > "$res_dir/speech.wav"
    """

  fileprivate static let emptyOutputScript = """
    #!/bin/sh
    set -eu
    IFS= read -r request
    exit 0
    """

  fileprivate static let nonWaveOutputScript = """
    #!/bin/sh
    set -eu
    res_dir=''
    while [ "$#" -gt 0 ]; do
      key="$1"
      value="$2"
      shift 2
      case "$key" in
        --res_dir) res_dir="$value" ;;
      esac
    done
    IFS= read -r request
    printf 'not-a-wave' > "$res_dir/speech.wav"
    """

  fileprivate static let oversizedOutputScript = """
    #!/bin/sh
    set -eu
    res_dir=''
    while [ "$#" -gt 0 ]; do
      key="$1"
      value="$2"
      shift 2
      case "$key" in
        --res_dir) res_dir="$value" ;;
      esac
    done
    IFS= read -r request
    /usr/bin/truncate -s 67108865 "$res_dir/speech.wav"
    """

  fileprivate static let longRunningScript = """
    #!/bin/sh
    set -eu
    umask 077
    model_dir=''
    while [ "$#" -gt 0 ]; do
      key="$1"
      value="$2"
      shift 2
      case "$key" in
        --model) model_dir="$value" ;;
      esac
    done
    /bin/sleep 30 &
    child="$!"
    trap 'kill -TERM "$child" 2>/dev/null || true; wait "$child" 2>/dev/null || true; exit 143' TERM INT
    printf '%s' "$child" > "$model_dir/child.pid"
    wait "$child"
    """
}

private final class Fixture: @unchecked Sendable {
  let rootURL: URL
  let executableURL: URL
  let modelDirectoryURL: URL
  let huggingFaceCacheURL: URL
  let referenceAudioURL: URL
  let temporaryRootURL: URL

  init(script: String) throws {
    rootURL = FileManager.default.temporaryDirectory.appendingPathComponent(
      UUID().uuidString,
      isDirectory: true
    )
    executableURL = rootURL.appendingPathComponent("synthetic-omnivoice", isDirectory: false)
    modelDirectoryURL = rootURL.appendingPathComponent("model", isDirectory: true)
    huggingFaceCacheURL = rootURL.appendingPathComponent("huggingface", isDirectory: true)
    referenceAudioURL = rootURL.appendingPathComponent("reference.wav", isDirectory: false)
    temporaryRootURL =
      rootURL
      .appendingPathComponent("Evie", isDirectory: true)
      .appendingPathComponent("TTS", isDirectory: true)

    try FileManager.default.createDirectory(
      at: rootURL,
      withIntermediateDirectories: false,
      attributes: [.posixPermissions: NSNumber(value: 0o700)]
    )
    try FileManager.default.createDirectory(
      at: modelDirectoryURL,
      withIntermediateDirectories: false,
      attributes: [.posixPermissions: NSNumber(value: 0o700)]
    )
    try FileManager.default.createDirectory(
      at: huggingFaceCacheURL,
      withIntermediateDirectories: false,
      attributes: [.posixPermissions: NSNumber(value: 0o700)]
    )
    try FileManager.default.createDirectory(
      at:
        huggingFaceCacheURL
        .appendingPathComponent("hub", isDirectory: true)
        .appendingPathComponent(
          "models--eustlb--higgs-audio-v2-tokenizer",
          isDirectory: true
        )
        .appendingPathComponent("snapshots", isDirectory: true)
        .appendingPathComponent("synthetic", isDirectory: true),
      withIntermediateDirectories: true,
      attributes: [.posixPermissions: NSNumber(value: 0o700)]
    )
    try Data(script.utf8).write(to: executableURL)
    try FileManager.default.setAttributes(
      [.posixPermissions: NSNumber(value: 0o700)],
      ofItemAtPath: executableURL.path
    )
    try Data("synthetic-reference".utf8).write(to: referenceAudioURL)
    try FileManager.default.setAttributes(
      [.posixPermissions: NSNumber(value: 0o600)],
      ofItemAtPath: referenceAudioURL.path
    )
  }

  func remove() {
    try? FileManager.default.removeItem(at: rootURL)
  }

  func configuration(
    timeout: TimeInterval = 2,
    gracePeriod: TimeInterval = 0.1
  ) -> OmniVoiceBatchTTSConfiguration {
    OmniVoiceBatchTTSConfiguration(
      executableURL: executableURL,
      modelDirectoryURL: modelDirectoryURL,
      huggingFaceCacheURL: huggingFaceCacheURL,
      temporaryRootURL: temporaryRootURL,
      timeout: timeout,
      terminationGracePeriod: gracePeriod
    )
  }

  func request() -> EvieTTSRequest {
    EvieTTSRequest(
      text: "PRIVATE-TEXT-SENTINEL",
      voiceReference: EvieTTSVoiceReference(
        audioFileURL: referenceAudioURL,
        transcript: "PRIVATE-REFERENCE-SENTINEL"
      )
    )
  }

  func permissions(at url: URL) throws -> Int {
    let attributes = try FileManager.default.attributesOfItem(atPath: url.path)
    return (attributes[.posixPermissions] as? NSNumber)?.intValue ?? -1
  }

  func requestDirectories() throws -> [URL] {
    guard FileManager.default.fileExists(atPath: temporaryRootURL.path) else { return [] }
    return try FileManager.default.contentsOfDirectory(
      at: temporaryRootURL,
      includingPropertiesForKeys: [.isDirectoryKey]
    )
  }

  /// Launches the script once and stops it again, before anything is timed.
  ///
  /// macOS charges the first execution of a file it has never seen a provenance
  /// check that the second execution of the same file does not pay. Measured on
  /// this machine, 200 launches of freshly written copies of the long-running
  /// script took 29 ms to reach the line that records the descendant's pid at
  /// the median, 324 ms at the 99th percentile and 450 ms at the worst, while
  /// 200 launches of one already-executed file never exceeded 41 ms. The timeout
  /// test gives the child 500 ms before killing its process group, so that tail
  /// fell on the wrong side of the deadline in about two runs per hundred: the
  /// script died before writing the pid file and the test failed reading it,
  /// which looked like a flaky adapter and was only a cold file. Paying the
  /// check before the clock starts puts the deadline back on the timeout.
  func warmUpExecutable() throws {
    let directory = rootURL.appendingPathComponent("warmup", isDirectory: true)
    try FileManager.default.createDirectory(
      at: directory,
      withIntermediateDirectories: false,
      attributes: [.posixPermissions: NSNumber(value: 0o700)]
    )
    let process = Process()
    process.executableURL = executableURL
    process.arguments = [
      "--model", directory.path,
      "--test_list", "/dev/stdin",
      "--res_dir", directory.path,
      "--nj_per_gpu", "1",
      "--batch_size", "1",
      "--warmup", "0",
      "--num_step", "32",
    ]
    process.standardInput = FileHandle.nullDevice
    process.standardOutput = FileHandle.nullDevice
    process.standardError = FileHandle.nullDevice
    try process.run()

    // Waiting for the pid file rather than for the launch, because the cost
    // being paid here covers the whole path the timed run has to walk: the
    // exec, the shell, and the fork of the descendant.
    let pidFileURL = directory.appendingPathComponent("child.pid", isDirectory: false)
    for _ in 0..<200 {
      if FileManager.default.fileExists(atPath: pidFileURL.path) {
        break
      }
      Thread.sleep(forTimeInterval: 0.005)
    }
    process.terminate()
    process.waitUntilExit()
  }

  func recordedChildIdentifier() async throws -> Int32 {
    let pidFileURL = modelDirectoryURL.appendingPathComponent("child.pid", isDirectory: false)
    for _ in 0..<40 {
      if let data = try? Data(contentsOf: pidFileURL),
        let value = Int32(String(decoding: data, as: UTF8.self))
      {
        return value
      }
      try await Task.sleep(for: .milliseconds(25))
    }
    throw FixtureError.childIdentifierMissing
  }

  func expectChildStopped(_ processIdentifier: Int32) async throws {
    for _ in 0..<80 {
      let state = try processState(processIdentifier)
      if state == nil || state == "Z" {
        return
      }
      try await Task.sleep(for: .milliseconds(25))
    }
    Issue.record("The synthetic descendant remained active after process-group termination.")
  }

  private func processState(_ processIdentifier: Int32) throws -> Character? {
    let process = Process()
    let output = Pipe()
    process.executableURL = URL(fileURLWithPath: "/bin/ps")
    process.arguments = ["-o", "state=", "-p", String(processIdentifier)]
    process.standardOutput = output
    process.standardError = FileHandle.nullDevice
    try process.run()
    process.waitUntilExit()
    let value = String(
      decoding: output.fileHandleForReading.readDataToEndOfFile(),
      as: UTF8.self
    ).trimmingCharacters(in: .whitespacesAndNewlines)
    return value.first
  }
}

private enum FixtureError: Error {
  case childIdentifierMissing
}
